print("Welcome to BMI Body Mass Calculator.")
height = input("enter your height in m: ")
weight = input("enter your weight in kg: ")
height_in_floate = float(height)
weight_in_floate = float(weight)
bmi = (height_in_floate/(weight_in_floate**2))
bmi_in_int = int(bmi)
bmi_str = str(bmi_in_int)
print("Your Body Mass is around : " + bmi_str)